---

root: true

env:
  es6: true
  browser: true
  webextensions: true

extends: standard

globals:
  _t: false
  GetAppIDFromUrl: false
  GetCurrentAppID: false
  GetHomepage: false
  GetLanguage: false
  GetLocalResource: false
  GetOption: false
  SendMessageToBackgroundScript: false
  SetOption: false
  WriteLog: false

rules:
  array-bracket-spacing: [error, always]
  brace-style: [error, allman]
  camelcase: off
  comma-dangle: [error, always-multiline]
  computed-property-spacing: [error, always]
  indent: [error, tab, {SwitchCase: 1}]
  keyword-spacing: [error, {before: false, after: false, overrides: {case: {after: true}, return: {after: true}, const: {after: true}, let: {after: true}, of: {before: true}, from: {before: true, after: true}}}]
  no-tabs: off
  no-trailing-spaces: [error]
  no-var: [error]
  object-curly-spacing: [error, always]
  prefer-const: [error]
  semi: [error, always]
  space-before-function-paren: [error, never]
  space-in-parens: [error, always]
  standard/no-callback-literal: off
  n/no-callback-literal: off
