preserve_hierarchy: true
files:
  - source: /_locales/en/messages.json
    translation: /_locales/%two_letters_code%/messages.json
    languages_mapping:
      two_letters_code:
        es-419: es_419
        pt-BR: pt_BR
        pt-PT: pt_PT
        zh-CN: zh_CN
        zh-TW: zh_TW
  - source: /assets/StoreReadme.txt
    translation: /store_readme/%language% (%locale_with_underscore%).txt
